import { WorkoutPlan } from "/Users/colinmack/Documents/Developer/tabata-app/src/app/workout-plan"
import { WorkoutSegment } from "/Users/colinmack/Documents/Developer/tabata-app/src/app/workout-segment"

export const WORKOUT_PLANS: WorkoutPlan[] = [
	{
		name : "5 Minute Core",
		sets : 1,
		prepTime : 10,
		exerciseTime: 15,
		restTime: 0,
		includeRests: false,
		segments : [
		{
			move : "Extended-Arm Plank",
			time : 60,
			color: "black",
			nextMove: "Alternating Bird Dogs",
			sound: "",
			beepValue: 4,
			finalBeep: false,
			lastSegmentInSet: false,
			started: false,
			blockId: ""

		},
		{
			move : "Alternating Bird Dogs",
			time : 30,
			color: "black",
			nextMove: "Armadillo",
			sound: "",
			beepValue: 4,
			finalBeep: false,
			lastSegmentInSet: false,
			started: false,
			blockId: ""
		},
		{
			move : "Armadillo",
			time : 30,
			color: "black",
			nextMove: "Table-Top Crunches",
			sound: "",
			beepValue: 4,
			finalBeep: false,
			lastSegmentInSet: false,
			started: false,
			blockId: ""
		},
		{
			move : "Table-Top Crunches",
			time : 30,
			color: "black",
			nextMove: "Roll-Ups",
			sound: "",
			beepValue: 4,
			finalBeep: false,
			lastSegmentInSet: false,
			started: false,
			blockId: ""
		},
		{
			move : "Roll-Ups",
			time : 30,
			color: "black",
			nextMove: "Forearm Plank",
			sound: "",
			beepValue: 4,
			finalBeep: false,
			lastSegmentInSet: false,
			started: false,
			blockId: ""
		},
		{
			move : "Forearm Plank",
			time : 30,
			color: "black",
			nextMove: "Leg Raises",
			sound: "",
			beepValue: 4,
			finalBeep: false,
			lastSegmentInSet: false,
			started: false,
			blockId: ""
		},
		{
			move : "Leg Raises",
			time : 30,
			color: "black",
			nextMove: "Twists",
			sound: "",
			beepValue: 4,
			finalBeep: false,
			lastSegmentInSet: false,
			started: false,
			blockId: ""
		},
		{
			move : "Twists",
			time : 30,
			color: "black",
			nextMove: "Bicycles",
			sound: "",
			beepValue: 4,
			finalBeep: false,
			lastSegmentInSet: false,
			started: false,
			blockId: ""
		},
		{
			move : "Bicycles",
			time : 30,
			color: "black",
			nextMove: "Done",
			sound: "",
			beepValue: 4,
			finalBeep: false,
			lastSegmentInSet: false,
			started: false,
			blockId: ""
		}]
	},
	{
		name : "Colin's Pre-Run Stretches",
		sets : 1, 
		prepTime : 10,
		exerciseTime: 15,
		restTime: 5,
		includeRests: true,
		segments: [
		{
			time: 60,
			color: "black",
			move: "Roll (Right)",
			nextMove: "Rest",
			sound: "",
			beepValue: 4,
			finalBeep: false,
			lastSegmentInSet: false,
			started: false,
			blockId: ""
		},
		{
			time: 60,
			color: "black",
			move: "Roll (Left)",
			nextMove: "Rest",
			sound: "",
			beepValue: 4,
			finalBeep: false,
			lastSegmentInSet: false,
			started: false,
			blockId: ""
		},
		{
			time: 15,
			color: "black",
			move: "Right Leg Toe Touch",
			nextMove: "Rest",
			sound: "",
			beepValue: 4,
			finalBeep: false,
			lastSegmentInSet: false,
			started: false,
			blockId: ""
		},
		{
			time: 15,
			color: "black",
			move: "Right Leg Toe Touch",
			nextMove: "Rest",
			sound: "",
			beepValue: 4,
			finalBeep: false,
			lastSegmentInSet: false,
			started: false,
			blockId: ""
		},		
		{
			time: 15,
			color: "black",
			move: "Right Leg Toe Touch",
			nextMove: "Rest",
			sound: "",
			beepValue: 4,
			finalBeep: false,
			lastSegmentInSet: false,
			started: false,
			blockId: ""
		},
		{
			time: 15,
			color: "black",
			move: "Pretzel - Right Over Left",
			nextMove: "Rest",
			sound: "",
			beepValue: 4,
			finalBeep: false,
			lastSegmentInSet: false,
			started: false,
			blockId: ""
		},
		{
			time: 15,
			color: "black",
			move: "Left Leg Toe Touch",
			nextMove: "Rest",
			sound: "",
			beepValue: 4,
			finalBeep: false,
			lastSegmentInSet: false,
			started: false,
			blockId: ""
		},
		{
			time: 15,
			color: "black",
			move: "Left Leg Toe Touch",
			nextMove: "Rest",
			sound: "",
			beepValue: 4,
			finalBeep: false,
			lastSegmentInSet: false,
			started: false,
			blockId: ""
		},
		{	
			time: 15,
			color: "black",
			move: "Left Leg Toe Touch",
			nextMove: "Rest",
			sound: "",
			beepValue: 4,
			finalBeep: false,
			lastSegmentInSet: false,
			started: false,
			blockId: ""
		},
		{
			time: 15,
			color: "black",
			move: "Pretzel - Left Over Right",
			nextMove: "Rest",
			sound: "",
			beepValue: 4,
			finalBeep: false,
			lastSegmentInSet: false,
			started: false,
			blockId: ""
		},
		{
			time: 15,
			color: "black",
			move: "Butterfly Stretch",
			nextMove: "Rest",
			sound: "",
			beepValue: 4,
			finalBeep: false,
			lastSegmentInSet: false,
			started: false,
			blockId: ""
		},
		{
			time: 15,
			color: "black",
			move: "Butterfly Stretch",
			nextMove: "Rest",
			sound: "",
			beepValue: 4,
			finalBeep: false,
			lastSegmentInSet: false,
			started: false,
			blockId: ""
		},
		{
			time: 15,
			color: "black",
			move: "Butterfly Stretch",
			nextMove: "Rest",
			sound: "",
			beepValue: 4,
			finalBeep: false,
			lastSegmentInSet: false,
			started: false,
			blockId: ""
		},
		{
			time: 15,
			color: "black",
			move: "Lunge (Left)",
			nextMove: "Rest",
			sound: "",
			beepValue: 4,
			finalBeep: false,
			lastSegmentInSet: false,
			started: false,
			blockId: ""
		},
		{
			time: 15,
			color: "black",
			move: "Deep Lunge (Left)",
			nextMove: "Rest",
			sound: "",
			beepValue: 4,
			finalBeep: false,
			lastSegmentInSet: false,
			started: false,
			blockId: ""
		},
		{
			time: 15,
			color: "black",
			move: "Lunge (Left)",
			nextMove: "Rest",
			sound: "",
			beepValue: 4,
			finalBeep: false,
			lastSegmentInSet: false,
			started: false,
			blockId: ""
		},
		{
			time: 15,
			color: "black",
			move: "Lunge (Right)",
			nextMove: "Rest",
			sound: "",
			beepValue: 4,
			finalBeep: false,
			lastSegmentInSet: false,
			started: false,
			blockId: ""
		},
		{
			time: 15,
			color: "black",
			move: "Deep Lunge (Right)",
			nextMove: "Rest",
			sound: "",
			beepValue: 4,
			finalBeep: false,
			lastSegmentInSet: false,
			started: false,
			blockId: ""
		},
		{
			time: 15,
			color: "black",
			move: "Lunge (Right)",
			nextMove: "Rest",
			sound: "",
			beepValue: 4,
			finalBeep: false,
			lastSegmentInSet: false,
			started: false,
			blockId: ""
		},
		{
			time: 15,
			color: "black",
			move: "Calf Stretch (Normal, Left)",
			nextMove: "Rest",
			sound: "",
			beepValue: 4,
			finalBeep: false,
			lastSegmentInSet: false,
			started: false,
			blockId: ""
		},
		{
			time: 15,
			color: "black",
			move: "Calf Stretch (Normal, Right)",
			nextMove: "Rest",
			sound: "",
			beepValue: 4,
			finalBeep: false,
			lastSegmentInSet: false,
			started: false,
			blockId: ""
		},
		{
			time: 15,
			color: "black",
			move: "Calf Stretch (Slant In, Left)",
			nextMove: "Rest",
			sound: "",
			beepValue: 4,
			finalBeep: false,
			lastSegmentInSet: false,
			started: false,
			blockId: ""
		},
		{
			time: 15,
			color: "black",
			move: "Calf Stretch (Slant In, Right)",
			nextMove: "Rest",
			sound: "",
			beepValue: 4,
			finalBeep: false,
			lastSegmentInSet: false,
			started: false,
			blockId: ""
		},
		{
			time: 15,
			color: "black",
			move: "Calf Stretch (Slant Out, Left)",
			nextMove: "Rest",
			sound: "",
			beepValue: 4,
			finalBeep: false,
			lastSegmentInSet: false,
			started: false,
			blockId: ""
		},
		{
			time: 15,
			color: "black",
			move: "Calf Stretch (Slant Out, Right)",
			nextMove: "Rest",
			sound: "",
			beepValue: 4,
			finalBeep: false,
			lastSegmentInSet: false,
			started: false,
			blockId: ""
		}]
	}
];